#!/usr/bin/env bash
# =============================================================================
# adapters/omp/adapter.sh - Oh My Pi platform adapter
# =============================================================================
# Oh My Pi reads AGENTS.md at the project (or vault) root as its operating
# manual. There is no native slash-command system, so we emit a dispatcher
# table in AGENTS.md that maps natural-language triggers to command files
# under .omp/commands/.
# =============================================================================

OMP_PLATFORM="omp"
OMP_DIR="omp"
OMP_DISPATCHER="AGENTS.md"

adapter_build() {
  local src="$1" dst="$2"

  _omp_emit_dispatcher "$src" "$dst"
  _omp_translate_commands "$src/commands" "$dst/.${OMP_DIR}/commands"
  _omp_copy_references "$src/references" "$dst/.${OMP_DIR}/references"
  _omp_copy_scripts "$src/scripts" "$dst/.${OMP_DIR}/scripts"
  _omp_emit_install_hint "$dst"
}

# Emit AGENTS.md at the dist root. Header + auto-generated routing table
# (one row per command, parsed from frontmatter description:).
_omp_emit_dispatcher() {
  local src="$1" dst="$2"
  local out="$dst/$OMP_DISPATCHER"

  {
    cat <<'EOF'
# Obsidian Second Brain - Oh My Pi Operating Manual

This vault runs the **obsidian-second-brain** skill. The skill ships a set of
*commands*: each one is a multi-step instruction file that you (the agent)
should follow when the user's request matches its trigger phrase.

## How to operate

1. Read `_AGENTS.md` in the vault root, if it exists, to learn the user's
   vault conventions (folder map, daily note format, naming).
2. When the user's request matches a trigger in the tables below, read the
   matching file under `.omp/commands/<name>.md` and follow its
   instructions step by step.
3. Treat the AI-first vault rule (`references/ai-first-rules.md`) as
   non-negotiable for every note you write: `## Synopsis` preamble,
   rich frontmatter (`type`, `date`, `tags`, `ai-first: true`), `[[wikilinks]]`
   for every person/project/concept, recency markers per external claim,
   sources verbatim, confidence levels where applicable.
4. Do not invent commands. If no command matches, ask the user what they
   want or fall back to plain natural-language help.

## Command routing tables (grouped by category)
EOF

    emit_routing_table_grouped "$src/commands" "$OMP_PLATFORM" ".omp/commands"
    emit_trigger_reference     "$src/commands" "$OMP_PLATFORM"

    cat <<'EOF'

## Trigger conventions

Each command file has a leading paragraph that documents its trigger phrases
in plain English. Treat those triggers as primary; the slash-form `/name` is
also accepted if the user types it.

## Scripts

Python helpers live under `.omp/scripts/`. They run via `uv run -m
scripts.research.<name>` from the vault root (or wherever the skill is
installed). The commands that need them reference the exact invocation
inside the command body.

---

*Generated by adapters/omp/adapter.sh - do not edit manually.*
EOF
  } > "$out"
}

# Copy commands into .omp/commands/, neutralizing Claude-specific tool
# names so the instructions still make sense for OMP agents.
_omp_translate_commands() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  local f out
  for f in "$src"/*.md; do
    [[ -f "$f" ]] || continue
    should_include "$f" "$OMP_PLATFORM" || continue
    out="$dst/$(basename "$f")"
    cp "$f" "$out"
    rewrite_tool_neutral "$out"
    rewrite_platform_paths "$out" "$OMP_DIR"
  done
}

_omp_copy_references() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  cp -R "$src/." "$dst/"
  find "$dst" -type f -name '*.md' -print0 | while IFS= read -r -d '' f; do
    rewrite_platform_paths "$f" "$OMP_DIR"
  done
}

_omp_copy_scripts() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  cp -R "$src/." "$dst/"
}

_omp_emit_install_hint() {
  local dst="$1"
  cat > "$dst/INSTALL.md" <<'EOF'
# Install on Oh My Pi

```bash
# From the repo root, after running `bash scripts/build.sh --platform omp`:
# The built tree is ready at dist/omp/. Install it:
bash scripts/install.sh --omp
```

Or manually:

```bash
# Symlink into Oh My Pi's skill directory:
SKILL_DIR=$(pwd)
ln -s "$SKILL_DIR" ~/.omp/agent/skills/obsidian-second-brain
```

Then set your vault path:

```bash
# Add to ~/.omp/agent/config.json or your agent's config:
# "OBSIDIAN_VAULT_PATH": "/path/to/your/vault"
```

Your agent will load the skill on the next session.
EOF
}
